# Generated by Django 4.2 on 2023-04-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicShock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_bs', models.CharField(max_length=30)),
                ('expected_arrival', models.CharField(max_length=30)),
                ('threshold_shocks', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CumulativeShock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_cs', models.CharField(max_length=30)),
                ('expected_arrival', models.CharField(max_length=30)),
                ('threshold_shocks', models.CharField(max_length=30)),
                ('mean_magnitude', models.CharField(max_length=30)),
                ('std_magnitude', models.CharField(max_length=30)),
                ('threshold_magnitude', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Degradation1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_d1', models.CharField(max_length=30)),
                ('z', models.CharField(max_length=30)),
                ('threshold', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Degradation2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_d2', models.CharField(max_length=30)),
                ('z', models.CharField(max_length=30)),
                ('threshold', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Degradation3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_d3', models.CharField(max_length=30)),
                ('z0', models.CharField(max_length=30)),
                ('z1', models.CharField(max_length=30)),
                ('threshold', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Degradation4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_d4', models.CharField(max_length=30)),
                ('z0', models.CharField(max_length=30)),
                ('z1', models.CharField(max_length=30)),
                ('threshold', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ExtremeShock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_es', models.CharField(max_length=30)),
                ('expected_arrival', models.CharField(max_length=30)),
                ('threshold_shocks', models.CharField(max_length=30)),
                ('mean_magnitude', models.CharField(max_length=30)),
                ('std_magnitude', models.CharField(max_length=30)),
                ('threshold_magnitude', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input1Value', models.CharField(max_length=50)),
                ('input2Value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Weibull',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_w', models.CharField(max_length=30)),
                ('eta', models.CharField(max_length=30)),
                ('beta', models.CharField(max_length=30)),
                ('reliability', models.CharField(max_length=30)),
            ],
        ),
    ]
