# Generated by Django 4.2 on 2023-04-19 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simulator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='degradation3',
            old_name='z1',
            new_name='y',
        ),
        migrations.RenameField(
            model_name='degradation3',
            old_name='z0',
            new_name='z',
        ),
        migrations.RenameField(
            model_name='degradation4',
            old_name='z1',
            new_name='y',
        ),
        migrations.RenameField(
            model_name='degradation4',
            old_name='z0',
            new_name='z',
        ),
    ]
