# Generated by Django 4.2 on 2023-04-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simulator', '0002_rename_z1_degradation3_y_rename_z0_degradation3_z_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weibull',
            old_name='reliability',
            new_name='low',
        ),
        migrations.RemoveField(
            model_name='degradation1',
            name='z',
        ),
        migrations.RemoveField(
            model_name='degradation2',
            name='z',
        ),
        migrations.RemoveField(
            model_name='degradation3',
            name='y',
        ),
        migrations.RemoveField(
            model_name='degradation3',
            name='z',
        ),
        migrations.RemoveField(
            model_name='degradation4',
            name='y',
        ),
        migrations.RemoveField(
            model_name='degradation4',
            name='z',
        ),
    ]
