# Generated by Django 4.2 on 2023-05-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulator', '0003_rename_reliability_weibull_low_remove_degradation1_z_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degradation5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_d5', models.CharField(max_length=30)),
                ('threshold', models.CharField(max_length=30)),
            ],
        ),
    ]
