# Generated by Django 4.2 on 2023-05-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulator', '0004_degradation5'),
    ]

    operations = [
        migrations.AddField(
            model_name='degradation1',
            name='p1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='degradation1',
            name='p2',
            field=models.FloatField(default=0.0),
        ),
    ]
