# Generated by Django 4.2 on 2023-05-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulator', '0005_degradation1_p1_degradation1_p2'),
    ]

    operations = [
        migrations.AddField(
            model_name='degradation1',
            name='dist',
            field=models.CharField(default='default_value', max_length=30),
        ),
    ]
