# Generated by Django 4.2 on 2023-05-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulator', '0007_degradation2_dist_degradation2_p1_degradation2_p2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degradation3',
            name='threshold',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='degradation4',
            name='threshold',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='degradation5',
            name='threshold',
            field=models.FloatField(default=0.0),
        ),
    ]
