# Generated by Django 4.2 on 2023-05-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulator', '0008_alter_degradation3_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='degradation5',
            name='dist',
            field=models.CharField(default='default_value', max_length=30),
        ),
    ]
