# Generated by Django 4.2 on 2023-05-15 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simulator', '0009_degradation5_dist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degradation5',
            name='p3',
        ),
        migrations.RemoveField(
            model_name='degradation5',
            name='p4',
        ),
    ]
