# Generated by Django 4.2 on 2023-05-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simulator', '0010_remove_degradation5_p3_remove_degradation5_p4'),
    ]

    operations = [
        migrations.AddField(
            model_name='degradation1',
            name='high_in',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='degradation1',
            name='low_in',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='degradation2',
            name='high_in',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='degradation2',
            name='low_in',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='degradation3',
            name='high_in',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='degradation3',
            name='low_in',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='degradation4',
            name='high_in',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='degradation4',
            name='low_in',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='degradation5',
            name='high_in',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='degradation5',
            name='low_in',
            field=models.FloatField(default=0.0),
        ),
    ]
