# Generated by Django 4.2 on 2023-06-12 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simulator', '0011_degradation1_high_in_degradation1_low_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weibull',
            name='low',
        ),
    ]
